15-3-dars_blog-test/blog/urls.py
from django.urls import path
from .views import front_page, single, search

app_name = 'blog'

urlpatterns = [
    path('', front_page, name='home'),
    path('search', search, name='search'),
    path('post-detail/<slug:slug>', single, name='single'),
]

15-3-dars_blog-test/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

15-3-dars_blog-test/blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Articles(models.Model):
    title = models.CharField(max_length=255)
    summary = models.CharField(max_length=255)
    image = models.ImageField(upload_to='image/')
    text = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=200, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_at',)
        verbose_name = 'Maqola'
        verbose_name_plural = 'Maqolalar'

    def __str__(self):
        return self.title

15-3-dars_blog-test/blog/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .models import Articles
from django.db.models import Q
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

def search(request):
    query = request.GET.get('query', '')
    posts  = Articles.objects.filter(Q(title__icontains=query) | Q(text__icontains=query))
    page = request.GET.get('page', 1)
    paginator = Paginator(posts, 2)


    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'query': query,
        'posts': posts,
    }

    return render(request, 'search.html', context)

def front_page(request):

    posts = Articles.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(posts, 2)


    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'posts': posts,
    }

    return render(request, 'home.html', context)


def single(request, slug):
    post = get_object_or_404(Articles, slug=slug)

    context = {
        'post': post,
    }

    return render(request, 'single.html', context)

15-3-dars_blog-test/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
  <header class="container py-3">
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
      <a href="{% url 'blog:home' %}" class="d-flex align-items-center text-dark text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
        <span class="fs-4">Blog Site</span>
      </a>

      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <form class="d-flex me-4 mb-3" method="get" action="/search">
          <input class="form-control me-2" name="query" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        <a class="me-3 py-2 text-dark text-decoration-none" href="#">Features</a>
        <a class="me-3 py-2 text-dark text-decoration-none" href="#">Enterprise</a>
        <a class="me-3 py-2 text-dark text-decoration-none" href="#">Support</a>
        <a class="py-2 text-dark text-decoration-none" href="#">Pricing</a>
      </nav>
    </div>

  </header>
      
  <main>
    {% block content %}
    {% endblock %}
  </main>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>

15-3-dars_blog-test/blog/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container"> 
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% include 'posts_loop.html' %}
      </div>
    </div>
    <!-- <div class="mt-5" style="text-align: center; margin: auto;">
    </div> -->
  </div>
{% include 'pagination.html' %}
{% endblock %}

15-3-dars_blog-test/blog/templates/pagination.html
{% if posts.has_other_pages %}
  <nav class="mt-5">
    <ul class="pagination justify-content-center">
        {% if posts.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ posts.previous_page_number}}" aria-label=Previous>O'tkazish</a>
          <!-- <span aria-hidden="true">&laquo;</span> -->
        </a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <span class="page-link" aria-hidden="true">&laquo;</span>
      </li>
      {% endif %}

      {% for p in posts.paginator.page_range %}
      {% if posts.number == p %}
      <li class="page-item"><a class="page-link" style="color: rgb(248, 3, 3);" href="#">{{ p }}</a></li>
      {% else %}
      <li class="page-item"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
      {% endif %}
      {% endfor %}

      {% if posts.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ posts.next_page_number }}" aria-label=Next>Qaytarish</a>
          <!-- <span aria-hidden="true">&laquo;</span> -->
        </a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <span class="page-link" aria-hidden="true">&laquo;</span>
      </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

15-3-dars_blog-test/blog/templates/posts_loop.html
{% for post in posts %}
    <div class="col">
    <div class="card shadow-sm">
        <a href="{% url 'blog:single' post.slug %}">
            <img src="{{ post.image.url }}" class="card-img-top" alt="" >
        </a>  
        <div class="card-body">
            <h4>{{ post.title|title }}</h4>
        <p class="card-text">{{ post.summary }}</p>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
            <a href="{% url 'blog:single' post.slug %}" type="button" class="btn btn-sm btn-outline-secondary">View</a>
            </div>
            <small class="text-muted">{{ post.created_at|timesince }}</small>
        </div>
        </div>
    </div>
    </div>
{% endfor %}

15-3-dars_blog-test/blog/templates/search.html
{% extends 'base.html' %}
{% block title %}Search{% endblock %}
{% block content %}
<div class="album py-5 bg-light">
    <div class="container"> 
        <h4 class="mb-5"><center>Search results</center></h4>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% if posts %}
        {% include 'posts_loop.html' %}
        {% else %} 
          <h5>Kechirasiz ushbu {{ query }}-ga most natijalar bizda mavjud emas.</h5>
        {% endif %}  
      </div>
    </div>
  </div>
  {% include 'pagination.html' %}
{% endblock %}

15-3-dars_blog-test/blog/templates/single.html
{% extends 'base.html' %}

{% block title %}Post Detail{% endblock %}

{% block content %}
<div class="p-5">
    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
            <img src="{{ post.image.url }}" width="25%" alt="">
            <h1 class="display-5 fw-bold">{{ post.title }}</h1>
            <p class="col-md-8 fs-4">{{ post.text }}</p>
            <span>
                <em>Author: {{ post.author|title }}</em>
            </span>
            <span class="ms-5">Time: {{ post.created_at|timesince|title }}</span>
        </div>
    </div>
</div>
{% endblock %}